// Define courses and sections
import { ref } from 'vue';

const courses = [
  {
    id: '12325',
    department: 'Department 1',
    name: 'Introduction to Programming',
    instructor: 'Al-Khwarizmi',
    courseCode: 'CS101',
    courseCredits: '3',
    enrolledStudents: 40,
    evaluated: 30,
  },
  {
    id: '61890',
    department: 'Department 2',
    name: 'Data Structures and Algorithms',
    instructor: 'Ibn al-Haytham',
    courseCode: 'CS202',
    courseCredits: '4',
    enrolledStudents: 35,
    evaluated: 28,
  },
  {
    id: '12341',
    department: 'Department 3',
    name: 'Web Development',
    instructor: 'Al-Farabi',
    courseCode: 'CS303',
    courseCredits: '3',
    enrolledStudents: 45,
    evaluated: 40,
  },
  {
    id: '67090',
    department: 'Department 2',
    name: 'Database Management',
    instructor: 'Ibn Sina',
    courseCode: 'CS404',
    courseCredits: '4',
    enrolledStudents: 50,
    evaluated: 45,
  },
  {
    id: '19345',
    department: 'Department 1',
    name: 'Software Engineering',
    instructor: 'Al-Biruni',
    courseCode: 'CS505',
    courseCredits: '3',
    enrolledStudents: 30,
    evaluated: 25,
  },
  {
    id: '60090',
    department: 'Department 3',
    name: 'Artificial Intelligence',
    instructor: 'Jabir ibn Hayyan',
    courseCode: 'CS606',
    courseCredits: '4',
    enrolledStudents: 55,
    evaluated: 50,
  },
  {
    id: '00345',
    department: 'Department 2',
    name: 'Operating Systems',
    instructor: 'Ibn Rushd',
    courseCode: 'CS707',
    courseCredits: '3',
    enrolledStudents: 38,
    evaluated: 32,
  },
];

// Question sections
const sections = [
  {
    id: 1,
    title: 'Evaluating the quality of content delivery',
    questions: [
      {
        id: 1,
        text: 'Explanation of the course material is clear and understandable',
        selectedOption: '',
        options: [
          { text: 'Strongly Disagree', value: 0 },
          { text: 'Disagree', value: 1 },
          { text: 'Neutral', value: 2 },
          { text: 'Agree', value: 3 },
          { text: 'Strongly Agree', value: 4 },
        ],
      },
      {
        id: 2,
        text: 'Course topics are clear and related to the course content.',
        selectedOption: '',
        options: [
          { text: 'Strongly Disagree', value: 0 },
          { text: 'Disagree', value: 1 },
          { text: 'Neutral', value: 2 },
          { text: 'Agree', value: 3 },
          { text: 'Strongly Agree', value: 4 },
        ],
      },
    ],
  },
  {
    id: 2,
    title: 'Evaluating the resources and references',
    questions: [
      {
        id: 1,
        text: 'Notes/presentations cover all course topics.',
        selectedOption: '',
        options: [
          { text: 'Strongly Disagree', value: 0 },
          { text: 'Disagree', value: 1 },
          { text: 'Neutral', value: 2 },
          { text: 'Agree', value: 3 },
          { text: 'Strongly Agree', value: 4 },
        ],
      },
      {
        id: 2,
        text: 'Course books/references (digital or physical) are reliable and up-to-date.',
        selectedOption: '',
        options: [
          { text: 'Strongly Disagree', value: 0 },
          { text: 'Disagree', value: 1 },
          { text: 'Neutral', value: 2 },
          { text: 'Agree', value: 3 },
          { text: 'Strongly Agree', value: 4 },
        ],
      },
      {
        id: 3,
        text: 'Clear audio and video in recorded lectures.',
        selectedOption: '',
        options: [
          { text: 'Strongly Disagree', value: 0 },
          { text: 'Disagree', value: 1 },
          { text: 'Neutral', value: 2 },
          { text: 'Agree', value: 3 },
          { text: 'Strongly Agree', value: 4 },
        ],
      },
    ],
  },
];

const students = ref([
  {
    id: 20134,
    name: 'Omar Al-Farouq',
    email: 'omar.alfarouq@university.edu',
    semester: 3,
    department: 'Department 1',
    enrolledCourses: 5,
    evaluated: 3,
    remaining: 2,
    role: 'student',
  },
  {
    id: 20135,
    name: 'Layla Al-Hassan',
    email: 'layla.alhassan@university.edu',
    semester: 2,
    department: 'Department 2',
    enrolledCourses: 7,
    evaluated: 5,
    remaining: 2,
    role: 'student',
  },
  {
    id: 20136,
    name: 'Khalid Al-Sabah',
    email: 'khalid.alsabah@university.edu',
    semester: 4,
    department: 'Department 3',
    enrolledCourses: 6,
    evaluated: 3,
    remaining: 3,
    role: 'student',
  },
  {
    id: 20137,
    name: 'Aisha Al-Mansoori',
    email: 'aisha.almansoori@university.edu',
    semester: 1,
    department: 'Department 1',
    enrolledCourses: 7,
    evaluated: 7,
    remaining: 0,
    role: 'student',
  },
  {
    id: 20138,
    name: 'Faisal Al-Nasser',
    email: 'faisal.elnasser@university.edu',
    semester: 3,
    department: 'Department 2',
    enrolledCourses: 5,
    evaluated: 3,
    remaining: 2,
    role: 'student',
  },
  {
    id: 20139,
    name: 'Hassan Al-Shehri',
    email: 'hassan.alshehri@university.edu',
    semester: 2,
    department: 'Department 3',
    enrolledCourses: 7,
    evaluated: 1,
    remaining: 6,
    role: 'student',
  },
  {
    id: 20140,
    name: 'Sara Al-Mansoori',
    email: 'sara.almansoori@university.edu',
    semester: 4,
    department: 'Department 1',
    enrolledCourses: 4,
    evaluated: 3,
    remaining: 1,
    role: 'student',
  },
  {
    id: 20141,
    name: 'Farah Ben Abdallah',
    email: 'farah.benabdallah@university.edu',
    semester: 4,
    department: 'Department 1',
    enrolledCourses: 6,
    evaluated: 3,
    remaining: 3,
    role: 'student',
  },
  {
    id: 20142,
    name: 'Khalid Bilal',
    email: 'khalid.bilal@university.edu',
    semester: 4,
    department: 'Department 1',
    enrolledCourses: 6,
    evaluated: 2,
    remaining: 4,
    role: 'student',
  },
  {
    id: 20143,
    name: 'Sami Khalil',
    email: 'sami.khalil@university.edu',
    semester: 4,
    department: 'Department 1',
    enrolledCourses: 7,
    evaluated: 3,
    remaining: 4,
    role: 'student',
  },
]);

export { courses, students, sections };
